import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";

const robot = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={robot.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
